#!/bin/bash
# Print environment details
echo "PATH:" "$PATH"
echo "USBEVENTMANAGER_PLATFORM: " "$USBEVENTMANAGER_PLATFORM"
echo "USBEVENTMANAGER_DEVICE_ID: " "$USBEVENTMANAGER_DEVICE_ID"
echo "USBEVENTMANAGER_EVENT_TYPE: " "$USBEVENTMANAGER_EVENT_TYPE"
exit 0
